import io
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from reportlab.lib.utils import ImageReader


def generate_pdf(dataset):
    """
    Generates a PDF report for a Dataset instance.
    Returns PDF as bytes.
    """
    # Lazy import: matplotlib only loads when PDF is generated
    # This prevents font cache build during startup
    import matplotlib
    matplotlib.use("Agg")  # Non-GUI backend - critical for server
    import matplotlib.pyplot as plt

    # -----------------------------
    # 1. Generate chart image
    # -----------------------------
    type_data = dataset.type_distribution

    fig, ax = plt.subplots()
    ax.bar(type_data.keys(), type_data.values())#Uses server-side Matplotlib
    ax.set_title("Equipment Type Distribution")
    ax.set_xlabel("Equipment Type")
    ax.set_ylabel("Count")

    chart_buffer = io.BytesIO()#Creates an in-memory file, No temp files on disk
    plt.savefig(chart_buffer, format="png", bbox_inches="tight")
    plt.close(fig)
    chart_buffer.seek(0)

    # -----------------------------
    # 2. Create PDF
    # -----------------------------
    pdf_buffer = io.BytesIO()
    pdf = canvas.Canvas(pdf_buffer, pagesize=A4)#Creates a blank PDF page
    width, height = A4

    y = height - 50

    # Title
    pdf.setFont("Helvetica-Bold", 16)
    pdf.drawString(50, y, "Chemical Equipment Visualizer")
    y -= 30

    pdf.setFont("Helvetica", 12)
    pdf.drawString(50, y, "Analysis Report")
    y -= 40

    # Metadata
    pdf.setFont("Helvetica", 10)
    pdf.drawString(50, y, f"Dataset Name: {dataset.name}")
    y -= 15
    pdf.drawString(50, y, f"Uploaded At: {dataset.uploaded_at.strftime('%d %b %Y %H:%M')}")
    y -= 30

    # Summary section
    pdf.setFont("Helvetica-Bold", 12)
    pdf.drawString(50, y, "Summary Statistics")
    y -= 20

    pdf.setFont("Helvetica", 10)
    pdf.drawString(50, y, f"Total Equipment: {dataset.total_equipment}")
    y -= 15
    pdf.drawString(50, y, f"Average Flowrate: {dataset.avg_flowrate}")
    y -= 15
    pdf.drawString(50, y, f"Average Pressure: {dataset.avg_pressure}")
    y -= 15
    pdf.drawString(50, y, f"Average Temperature: {dataset.avg_temperature}")
    y -= 30

    # Chart image
    chart_image = ImageReader(chart_buffer)

    pdf.drawImage(
    chart_image,
    50,
    y - 250,
    width=width - 100,
    height=250,
    preserveAspectRatio=True
)


    # Footer
    pdf.setFont("Helvetica-Oblique", 9)
    pdf.drawString(50, 40, "Generated by Chemical Equipment Visualizer")

    pdf.showPage()
    pdf.save()

    pdf_buffer.seek(0)
    return pdf_buffer.getvalue()
